:mod:`fldatamigration.fl.datamigration.exceptions.corrupted_data_exception`
===========================================================================

.. py:module:: fldatamigration.fl.datamigration.exceptions.corrupted_data_exception


Module Contents
---------------

.. py:exception:: CorruptedDataException(*args)

   Bases: :class:`fl.datamigration.exceptions.invalid_exception.InvalidException`

   .. method:: __str__(self)




